
MODULE INITIALIZATION          msecs      invoked at
pre-Module.Startup               307    10:57:37.901
NodeBase.NbModule...                    10:57:38.208
...initialized                   102
NodeTools.NtModule...                   10:57:38.319
...initialized                    36
CodeTools.CtModule...                   10:57:38.364
...initialized                    28
NetworkBase.NwModule...                 10:57:38.400

    NET500 20-Dec-2020 10:57:38.416 on Reigi {1}
...initialized                    97
SessionBase.SbModule...                 10:57:38.505
...initialized                   113
ControlNode.CnModule...                 10:57:38.628
...initialized                     8
SessionTools.StModule...                10:57:38.647
...initialized                    18
MediaBase.MbModule...                   10:57:38.681
...initialized                    16
CallBase.CbModule...                    10:57:38.708
...initialized                    23
PotsBase.PbModule...                    10:57:38.740
...initialized                    31
OperationsNode.OnModule...              10:57:38.783
...initialized                    12
RoutingNode.RnModule...                 10:57:38.807
...initialized                    11
ServiceNode.SnModule...                 10:57:38.831
...initialized                    42
AccessNode.AnModule...                  10:57:38.883
...initialized                    19
                               -----
total initialization time       1013

    NODE500 20-Dec-2020 10:57:38.926 on Reigi {2}
nb>read test.trap.all

nb>read test.trap.setup
nb>quit all
  Nothing to quit.
nb>nt
nt>swflags set &flag.reenterthread on
  OK.
nt>read test.tools.setup
nt>stop
  OK.
nt>clear buffer
  OK.
nt>clear selections
  OK.
nt>clear tools
  OK.
nt>set tools f on
  f: OK.
  OK.
nt>/ set scope counts  / enables full function trace if commented out
nt>include all on
  OK.
nt>read test.trap.tools.setup
nt>/ This only leaves LoadTestFaction, to which RecoveryThread belongs,
nt>/ traced. Including SystemFaction (InitThread) would show Daemon work
nt>/ but would also make the traces much longer, because InitThread runs
nt>/ well before, and after, RecoveryThread.
nt>/
nt>exclude faction &faction.audit
  OK.
nt>exclude faction &faction.bkgd
  OK.
nt>exclude faction &faction.oper
  OK.
nt>exclude faction &faction.mtce
  OK.
nt>exclude faction &faction.payload
  OK.
nt>exclude faction &faction.system
  OK.
nt>exclude faction &faction.watchdog
  OK.
nt>tests prolog test.trap.prolog
  OK.
nt>tests epilog test.trap.epilog
  OK.
nt>recover create
  OK.
nt>tests begin recover.Return
symbols set test.name recover.Return
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.01
nt>/ RECOVER return
nt>recover return
nt>
    THR901 20-Dec-2020 10:57:54.969 on Reigi {3}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00005750)
    signal=0 (Normal Exit)
tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.Return completed.
nt>tests begin recover.SwErr
symbols set test.name recover.SwErr
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.02
nt>/ RECOVER swerr
nt>recover swerr
nt>
    THR902 20-Dec-2020 10:57:56.808 on Reigi {4}
    in NodeTools.RecoveryThread (tid=15, nid=0x00005ec8): trap number 1
    type=Software Error
    errstr : software error test
    offset : 0x1
    Function Traceback:
      NodeBase.SoftwareException.SoftwareException @ softwareexception.cpp + 46[15]
      NodeBase.Debug.SwErr @ debug.cpp + 146[22]
      NodeTools.RecoveryThread.DoSwErr @ ntincrement.cpp + 3964[33]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4049[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.SwErr completed.
nt>tests begin recover.BadPtrExit
symbols set test.name recover.BadPtrExit
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.24
nt>/ RECOVER dereference bad pointer and exit thread
nt>swflags set &flag.reenterthread off
nt>delay 1
nt>recover badptr
nt>
    THR902 20-Dec-2020 10:57:59.422 on Reigi {5}
    in NodeTools.RecoveryThread (tid=15, nid=0x00005ec8): trap number 2
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 145[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4113[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4015[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR901 20-Dec-2020 10:57:59.423 on Reigi {6}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00005ec8)
    signal=11 (SIGSEGV: Invalid Memory Reference)
delay 1
nt>swflags set &flag.reenterthread on
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.BadPtrExit completed.
nt>tests begin recover.BadPtr
symbols set test.name recover.BadPtr
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.03
nt>/ RECOVER dereference bad pointer
nt>recover badptr

    THR902 20-Dec-2020 10:58:02.218 on Reigi {7}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003164): trap number 3
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 145[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4113[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4015[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.BadPtr completed.
nt>tests begin recover.DivZero
symbols set test.name recover.DivZero
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.04
nt>/ RECOVER divide by zero
nt>recover divide

    THR902 20-Dec-2020 10:58:03.661 on Reigi {8}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003164): trap number 4
    type=Signal
    signal : 8 (SIGFPE: Erroneous Arithmetic Operation)
    errval : 0xc0000094
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 145[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4018[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.DivZero completed.
nt>tests begin recover.SIGINT
symbols set test.name recover.SIGINT
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.05
nt>/ RECOVER raise interrupt
nt>recover raise SIGINT

    THR902 20-Dec-2020 10:58:05.151 on Reigi {9}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003164): trap number 5
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 2929[11]
      raise @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoRaise @ ntincrement.cpp + 3955[15]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4042[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.SIGINT completed.
nt>tests begin recover.SIGILL
symbols set test.name recover.SIGILL
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.06
nt>/ RECOVER raise illegal instruction
nt>recover raise SIGILL

    THR902 20-Dec-2020 10:58:06.636 on Reigi {10}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003164): trap number 6
    type=Signal
    signal : 4 (SIGILL: Illegal Instruction)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 2929[11]
      raise @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoRaise @ ntincrement.cpp + 3955[15]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4042[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.SIGILL completed.
nt>tests begin recover.SIGTERM
symbols set test.name recover.SIGTERM
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.07
nt>/ RECOVER raise termination from kill
nt>recover raise SIGTERM

    THR902 20-Dec-2020 10:58:08.115 on Reigi {11}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003164): trap number 7
    type=Signal
    signal : 15 (SIGTERM: Termination Request)
    errval : 0x0
    TRAP LIMIT EXCEEDED.
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 2929[11]
      raise @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoRaise @ ntincrement.cpp + 3955[15]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4042[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR906 20-Dec-2020 10:58:08.115 on Reigi {12}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00003164)
    signal=15 (SIGTERM: Termination Request)
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.SIGTERM completed.
nt>tests begin recover.SIGBREAK
symbols set test.name recover.SIGBREAK
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.08
nt>/ RECOVER raise ctrl-break
nt>recover raise SIGBREAK

    THR902 20-Dec-2020 10:58:09.604 on Reigi {13}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003f04): trap number 8
    type=Signal
    signal : 21 (SIGBREAK: Ctrl-Break)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 2929[11]
      raise @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoRaise @ ntincrement.cpp + 3955[15]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4042[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.SIGBREAK completed.
nt>tests begin recover.abort
symbols set test.name recover.abort
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.09
nt>/ ============== PREPARE TO CLICK RETRY, THEN CONTINUE (F5) ==============
nt>/ RECOVER abort
nt>/ Enable breakpoints because of pop-up dialog.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover abort

    THR902 20-Dec-2020 10:58:16.687 on Reigi {14}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003f04): trap number 9
    type=Signal
    signal : 22 (SIGABRT: Abort Request)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 2929[11]
      raise @ <unknown file> (err=487)
      abort @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoAbort @ ntincrement.cpp + 3927[8]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4006[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>delay 1
nt>cfgparms set breakenabled &save.breakenabled
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.abort completed.
nt>tests begin recover.terminate
symbols set test.name recover.terminate
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.10
nt>/ ============== PREPARE TO CLICK RETRY, THEN CONTINUE (F5) ==============
nt>/ RECOVER terminate
nt>/ Enable breakpoints because of pop-up dialog.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover terminate

    THR902 20-Dec-2020 10:58:23.809 on Reigi {15}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003f04): trap number 10
    type=Signal
    signal : 22 (SIGABRT: Abort Request)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.Thread.SignalHandler @ thread.cpp + 2929[11]
      raise @ <unknown file> (err=487)
      abort @ <unknown file> (err=487)
      terminate @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoTerminate @ ntincrement.cpp + 3973[8]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4052[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>delay 1
nt>cfgparms set breakenabled &save.breakenabled
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.terminate completed.
nt>tests begin recover.KillLocal
symbols set test.name recover.KillLocal
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.11
nt>/ RECOVER kill this
nt>recover trap t SIGPURGE

    THR902 20-Dec-2020 10:58:26.729 on Reigi {16}
    in NodeTools.RecoveryThread (tid=15, nid=0x00003f04): trap number 11
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.Raise @ thread.cpp + 2478[19]
      NodeTools.RecoveryThread.DoTrap @ ntincrement.cpp + 3982[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4055[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 0357D758
      patchArea : 0x0
      systhrd  : 06B981C8
        NodeBase.SysThread
        this : 06B981C8
        patchArea : 0x0
        nthread  : 000003D4
        nid      : 3f04
        status   : 000
        event    : 000003D0
        guard    : 0000033C
        priority : 1
        signal   : 0
      daemon   : 03598900 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 03365A20
        patchArea : 0x0
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        swlogs     : 0
        entered    : true
        waiting    : false
        locked     : true
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        blocked    : ready
        status     : unspecified
        signal     : 126
        stackBase  : 06ABF734
        acquiring  : 00000000
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 03365A48
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496131613451
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 03365A68
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496296494256
          limit    : 4
          count    : 3
        vector     : 0
        prevTime   : 29966826
        currTime   : 0
        readyTime  : 1496317713958
        currStart  : 1496317717082
        currEnd    : 1496319517082
      test   : 0
      signal : 126
nt>
    THR901 20-Dec-2020 10:58:26.730 on Reigi {17}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00003f04)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.KillLocal completed.
nt>tests begin recover.KillRemote
symbols set test.name recover.KillRemote
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.12
nt>/ RECOVER kill remotely
nt>recover trap f SIGPURGE

    THR903 20-Dec-2020 10:58:28.207 on Reigi {18}
    by NodeBase.CliThread (tid=9, nid=0x00001cd4)
    for NodeTools.RecoveryThread (tid=15, nid=0x0000168c)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

    THR902 20-Dec-2020 10:58:28.211 on Reigi {19}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000168c): trap number 12
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1674[31]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3506[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1799[0]
      NodeBase.Debug.ft @ debug.cpp + 74[9]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1615[10]
      NodeBase.Thread.Pause @ thread.cpp + 2368[11]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4064[26]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 03581F18
      patchArea : 0x0
      systhrd  : 06B984F8
        NodeBase.SysThread
        this : 06B984F8
        patchArea : 0x0
        nthread  : 000004C8
        nid      : 168c
        status   : 000
        event    : 000004DC
        guard    : 000004E0
        priority : 1
        signal   : 0
      daemon   : 03598900 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 033661A0
        patchArea : 0x0
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        swlogs     : 0
        entered    : true
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        blocked    : clock
        status     : unspecified
        signal     : 126
        stackBase  : 0942F838
        acquiring  : 00000000
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 033661C8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496317765923
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 033661E8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496332558247
          limit    : 4
          count    : 1
        vector     : 0
        prevTime   : 0
        currTime   : 1048
        readyTime  : 1496317801301
        currStart  : 1496332528669
        currEnd    : 200000
      test   : 0
      signal : 0
nt>
    THR901 20-Dec-2020 10:58:28.211 on Reigi {20}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000168c)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.KillRemote completed.
nt>tests begin recover.InfiniteLoop
symbols set test.name recover.InfiniteLoop
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.13
nt>/ RECOVER infinite loop
nt>/ Enable use of SIGYIELD to kill thread that runs too long.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled f
nt>symbols assign save.traponrtctimeout traponrtctimeout
nt>cfgparms set traponrtctimeout t
nt>delay 1
nt>recover loop

    THR903 20-Dec-2020 10:58:31.136 on Reigi {21}
    by NodeBase.InitThread (tid=2, nid=0x000059b0)
    for NodeTools.RecoveryThread (tid=15, nid=0x000054a4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR902 20-Dec-2020 10:58:31.148 on Reigi {22}
    in NodeTools.RecoveryThread (tid=15, nid=0x000054a4): trap number 13
    type=Signal
    signal : 123 (SIGYIELD: Running Unpreemptably Too Long)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1674[31]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3506[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1799[0]
      NodeBase.Debug.ft @ debug.cpp + 74[9]
      NodeTools.RecoveryThread.LoopForever @ ntincrement.cpp + 4083[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4024[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>delay 1
nt>cfgparms set traponrtctimeout &save.traponrtctimeout
nt>cfgparms set breakenabled &save.breakenabled
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.InfiniteLoop completed.
nt>tests begin recover.StackOverflow
symbols set test.name recover.StackOverflow
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.14
nt>/ ============== THE STACK OVERFLOW MAY TAKE TIME TO OCCUR ===============
nt>/ RECOVER stack overflow
nt>/ Enable breakpoints to provide time for overflow.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover stack

    THR902 20-Dec-2020 10:58:34.960 on Reigi {23}
    in NodeTools.RecoveryThread (tid=15, nid=0x000054a4): trap number 14
    type=Signal
    signal : 124 (SIGSTACK1: Stack Overflow: Attempt Recovery)
    errval : 0x1f43
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.StackCheck @ thread.cpp + 2976[16]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1807[0]
      NodeBase.Debug.ft @ debug.cpp + 74[9]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4101[10]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      ...1997 functions omitted.
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 4103[12]
nt>delay 1
nt>cfgparms set breakenabled &save.breakenabled
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.StackOverflow completed.
nt>tests begin recover.MutexBlock
symbols set test.name recover.MutexBlock
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.19
nt>/ RECOVER block while holding mutex
nt>recover mutexblock

    SW900 20-Dec-2020 10:58:39.029 on Reigi {24}
    in Thread.EnterBlockingOperation
    expl=mutex holder  errval=0x1
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 191[24]
      NodeBase.Thread.EnterBlockingOperation @ thread.cpp + 1535[56]
      NodeBase.Thread.Pause @ thread.cpp + 2365[14]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4027[26]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.MutexBlock completed.
nt>tests begin recover.MutexExit
symbols set test.name recover.MutexExit
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.21
nt>/ RECOVER exit while holding mutex
nt>recover mutexexit

    THR907 20-Dec-2020 10:58:40.484 on Reigi {25}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000054a4)
    mutexes=1

    THR901 20-Dec-2020 10:58:40.485 on Reigi {26}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000054a4)
    signal=0 (Normal Exit)
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.MutexExit completed.
nt>tests begin recover.MutexTrap
symbols set test.name recover.MutexTrap
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.22
nt>/ RECOVER trap while holding mutex
nt>recover mutextrap

    THR907 20-Dec-2020 10:58:41.971 on Reigi {27}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000052d4)
    mutexes=1

    THR902 20-Dec-2020 10:58:41.972 on Reigi {28}
    in NodeTools.RecoveryThread (tid=15, nid=0x000052d4): trap number 15
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 145[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4113[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4036[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.MutexTrap completed.
nt>tests begin recover.TrapInRecover
symbols set test.name recover.TrapInRecover
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.15
nt>/ RECOVER trap during recovery
nt>swflags set &flag.recovertrap on
nt>delay 1
nt>recover swerr

    THR902 20-Dec-2020 10:58:44.491 on Reigi {29}
    in NodeTools.RecoveryThread (tid=15, nid=0x000052d4): trap number 16
    type=Software Error
    errstr : software error test
    offset : 0x1
    Function Traceback:
      NodeBase.SoftwareException.SoftwareException @ softwareexception.cpp + 46[15]
      NodeBase.Debug.SwErr @ debug.cpp + 146[22]
      NodeTools.RecoveryThread.DoSwErr @ ntincrement.cpp + 3964[33]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4049[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 20-Dec-2020 10:58:44.495 on Reigi {30}
    in NodeTools.RecoveryThread (tid=15, nid=0x000052d4): trap number 17
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    TRAP DURING RECOVERY.
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 145[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4113[0]
      NodeTools.RecoveryThread.Recover @ ntincrement.cpp + 4094[0]
      NodeBase.Thread.Start @ thread.cpp + 3064[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>delay 1
nt>swflags set &flag.recovertrap off
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.TrapInRecover completed.
nt>tests begin recover.ThreadCtorTrap
symbols set test.name recover.ThreadCtorTrap
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.20
nt>/ RECOVER thread constructor trap
nt>/ InitThread will trap when it invokes RecoveryDaemon.CreateThread
nt>/ to recreate the recovery thread.
nt>recover ctortrap

    THR901 20-Dec-2020 10:58:47.223 on Reigi {31}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000052d4)
    signal=0 (Normal Exit)

    THR900 20-Dec-2020 10:58:47.244 on Reigi {32}
    thread=NodeBase.Thread (tid=15, nid=0x000049cc)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 185[9]
      NodeBase.Thread.~Thread @ thread.cpp + 1142[16]
      NLG_Return @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 82[34]
      NodeTools.RecoveryDaemon.CreateThread @ ntincrement.cpp + 3831[0]
      NodeBase.Daemon.CreateThreads @ daemon.cpp + 125[15]
      NodeBase.InitThread.RecreateThreads @ initthread.cpp + 405[0]
      NodeBase.InitThread.HandleInterrupt @ initthread.cpp + 294[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 245[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 03581C98
      patchArea : 0x0
      systhrd  : 06B97F58
        NodeBase.SysThread
        this : 06B97F58
        patchArea : 0x0
        nthread  : 000004C0
        nid      : 49cc
        status   : 000
        event    : 000002BC
        guard    : 000004F4
        priority : 1
        signal   : 0
      daemon   : 03598900 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 03365700
        patchArea : 0x0
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        swlogs     : 0
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        blocked    : ready
        status     : unspecified
        signal     : 0
        stackBase  : 00000000
        acquiring  : 00000000
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 03365728
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496522696403
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 03365748
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496522696461
          limit    : 4
          count    : 0
        vector     : 0
        prevTime   : 0
        currTime   : 0
        readyTime  : 0
        currStart  : 0
        currEnd    : 0
nt>
    SW900 20-Dec-2020 10:58:47.249 on Reigi {33}
    in ThreadRegistry.GetState
    expl=orphan exited  errval=0x49cc
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 191[24]
      NodeBase.ThreadRegistry.GetState @ threadregistry.cpp + 299[42]
      NodeBase.Thread.Start @ thread.cpp + 3010[8]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 20-Dec-2020 10:58:47.256 on Reigi {34}
    in NodeBase.InitThread (tid=2, nid=0x000059b0): trap number 18
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 145[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4113[0]
      NodeTools.RecoveryThread.RecoveryThread @ ntincrement.cpp + 3859[0]
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 82[34]
      NodeTools.RecoveryDaemon.CreateThread @ ntincrement.cpp + 3831[0]
      NodeBase.Daemon.CreateThreads @ daemon.cpp + 125[15]
      NodeBase.InitThread.RecreateThreads @ initthread.cpp + 405[0]
      NodeBase.InitThread.HandleInterrupt @ initthread.cpp + 294[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 245[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.ThreadCtorTrap completed.
nt>tests begin recover.DaemonReenable
symbols set test.name recover.DaemonReenable
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.25
nt>/ RECOVER disable daemon; kill thread; enable daemon; thread recreated
nt>daemons set 9 off
nt>delay 1
nt>sched kill 15

    THR903 20-Dec-2020 10:58:49.961 on Reigi {35}
    by NodeBase.CliThread (tid=9, nid=0x00001cd4)
    for NodeTools.RecoveryThread (tid=15, nid=0x00005afc)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

    THR902 20-Dec-2020 10:58:49.965 on Reigi {36}
    in NodeTools.RecoveryThread (tid=15, nid=0x00005afc): trap number 19
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1674[31]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3506[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1799[0]
      NodeBase.Debug.ft @ debug.cpp + 74[9]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1615[10]
      NodeBase.Thread.Pause @ thread.cpp + 2368[11]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4064[26]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 03582018
      patchArea : 0x0
      systhrd  : 06E34280
        NodeBase.SysThread
        this : 06E34280
        patchArea : 0x0
        nthread  : 00000418
        nid      : 5afc
        status   : 000
        event    : 00000498
        guard    : 00000494
        priority : 1
        signal   : 0
      daemon   : 03598900 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 033661A0
        patchArea : 0x0
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        swlogs     : 0
        entered    : true
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        blocked    : clock
        status     : unspecified
        signal     : 126
        stackBase  : 06ABFCF0
        acquiring  : 00000000
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 033661C8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496523020267
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 033661E8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496550106746
          limit    : 4
          count    : 1
        vector     : 0
        prevTime   : 0
        currTime   : 808
        readyTime  : 1496523038827
        currStart  : 1496550078167
        currEnd    : 200000
      test   : 0
      signal : 0
nt>
    THR901 20-Dec-2020 10:58:49.966 on Reigi {37}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x00005afc)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

  * THR300 20-Dec-2020 10:58:49.967 on Reigi {38}
    Alarm ON: DAEMON10 (Thread(s) unavailable: recover)
    daemon=recover target=1 actual=0
delay 2
nt>daemons set 9 on
nt>delay 1
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.DaemonReenable completed.
nt>tests begin recover.DaemonRetrap
symbols set test.name recover.DaemonRetrap
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.26
nt>/ RECOVER daemon retraps trying to recreate thread; reenable to create thread
nt>swflags set &flag.threadctorretrap on
nt>delay 1
nt>recover ctortrap

    THR900 20-Dec-2020 10:58:55.812 on Reigi {39}
    thread=NodeBase.Thread (tid=15, nid=0x000046d0)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 185[9]
      NodeBase.Thread.~Thread @ thread.cpp + 1142[16]
      NLG_Return @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 82[34]
      NodeTools.RecoverCommand.EnsureThread @ ntincrement.cpp + 4414[5]
      NodeTools.RecoverCommand.ProcessCommand @ ntincrement.cpp + 4436[9]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 443[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 627[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 291[17]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 03582058
      patchArea : 0x0
      systhrd  : 06E34280
        NodeBase.SysThread
        this : 06E34280
        patchArea : 0x0
        nthread  : 000004CC
        nid      : 46d0
        status   : 000
        event    : 000004D4
        guard    : 00000480
        priority : 1
        signal   : 0
      daemon   : 03598900 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 03365B60
        patchArea : 0x0
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        swlogs     : 0
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        blocked    : ready
        status     : unspecified
        signal     : 0
        stackBase  : 00000000
        acquiring  : 00000000
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 03365B88
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496608453250
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 03365BA8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496608453283
          limit    : 4
          count    : 0
        vector     : 0
        prevTime   : 0
        currTime   : 0
        readyTime  : 0
        currStart  : 0
        currEnd    : 0
nt>
    SW900 20-Dec-2020 10:58:55.814 on Reigi {40}
    in ThreadRegistry.GetState
    expl=orphan exited  errval=0x46d0
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 191[24]
      NodeBase.ThreadRegistry.GetState @ threadregistry.cpp + 299[42]
      NodeBase.Thread.Start @ thread.cpp + 3010[8]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 20-Dec-2020 10:58:55.815 on Reigi {41}
    in NodeBase.CliThread (tid=9, nid=0x00001cd4): trap number 20
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 145[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4113[0]
      NodeTools.RecoveryThread.RecoveryThread @ ntincrement.cpp + 3865[0]
      NodeBase.Singleton<NodeTools.RecoveryThread>.Instance @ singleton.h + 82[34]
      NodeTools.RecoverCommand.EnsureThread @ ntincrement.cpp + 4414[5]
      NodeTools.RecoverCommand.ProcessCommand @ ntincrement.cpp + 4436[9]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 443[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 627[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 291[17]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 1
nt>daemons set 9 on
nt>delay 1
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.DaemonRetrap completed.
nt>tests begin recover.DeleteRemote
symbols set test.name recover.DeleteRemote
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.16
nt>/ RECOVER destroy remotely
nt>/ After deleting the thread, give it time to wake up and exit.
nt>recover delete f

    SW900 20-Dec-2020 10:58:59.596 on Reigi {42}
    in RecoverCommand.EnsureThread
    expl=recovery thread created  errval=0x0
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 191[24]
      NodeTools.RecoverCommand.EnsureThread @ ntincrement.cpp + 4417[42]
      NodeTools.RecoverCommand.ProcessCommand @ ntincrement.cpp + 4436[9]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 443[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 627[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 291[17]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR900 20-Dec-2020 10:58:59.597 on Reigi {43}
    thread=NodeBase.Thread (tid=15, nid=0x00001324)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 185[9]
      NodeBase.Thread.~Thread @ thread.cpp + 1142[16]
      NodeTools.RecoveryThread.~RecoveryThread @ ntincrement.cpp + 3879[15]
      NodeTools.RecoveryThread.`scalar deleting destructor' @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Destroy @ singleton.h + 106[34]
      NodeTools.RecoverCommand.ProcessCommand @ ntincrement.cpp + 4475[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 443[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 627[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 291[17]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 03581C18
      patchArea : 0x0
      systhrd  : 06E378E0
        NodeBase.SysThread
        this : 06E378E0
        patchArea : 0x0
        nthread  : 00000494
        nid      : 1324
        status   : 000
        event    : 0000048C
        guard    : 000003D0
        priority : 1
        signal   : 0
      daemon   : 03598900 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 03365E80
        patchArea : 0x0
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        swlogs     : 0
        entered    : false
        waiting    : true
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        blocked    : ready
        status     : unspecified
        signal     : 0
        stackBase  : 00000000
        acquiring  : 00000000
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 03365EA8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496646394346
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 03365EC8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496646394400
          limit    : 4
          count    : 0
        vector     : 0
        prevTime   : 0
        currTime   : 0
        readyTime  : 1496646410718
        currStart  : 1496646410620
        currEnd    : 0
nt>delay 5
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.DeleteRemote completed.
nt>tests begin recover.DeleteLocal
symbols set test.name recover.DeleteLocal
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.17
nt>/ RECOVER destroy this
nt>recover delete t

    SW900 20-Dec-2020 10:59:06.261 on Reigi {44}
    in RecoverCommand.EnsureThread
    expl=recovery thread created  errval=0x0
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 191[24]
      NodeTools.RecoverCommand.EnsureThread @ ntincrement.cpp + 4417[42]
      NodeTools.RecoverCommand.ProcessCommand @ ntincrement.cpp + 4436[9]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 443[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 627[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 291[17]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>
    THR900 20-Dec-2020 10:59:06.272 on Reigi {45}
    thread=NodeBase.Thread (tid=15, nid=0x00000448)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 185[9]
      NodeBase.Thread.~Thread @ thread.cpp + 1142[16]
      NodeTools.RecoveryThread.~RecoveryThread @ ntincrement.cpp + 3879[15]
      NodeTools.RecoveryThread.`scalar deleting destructor' @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Destroy @ singleton.h + 106[34]
      NodeTools.RecoveryThread.DoDelete @ ntincrement.cpp + 3937[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4012[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 03581BD8
      patchArea : 0x0
      systhrd  : 06E37730
        NodeBase.SysThread
        this : 06E37730
        patchArea : 0x0
        nthread  : 00000480
        nid      : 0448
        status   : 000
        event    : 000004B4
        guard    : 000004CC
        priority : 1
        signal   : 0
      daemon   : 03598900 NodeTools.RecoveryDaemon
      tid      : 15
      faction  : 6
      deleting : false
      msgq     : 
        tail : 00000000
        diff : 8
      priv     : 
        NodeBase.ThreadPriv
        this : 03365B60
        patchArea : 0x0
        unpreempts : 1
        immUnprots : 0
        memUnprots : 0
        mutexes    : 0
        swlogs     : 0
        entered    : true
        waiting    : false
        locked     : true
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        blocked    : ready
        status     : unspecified
        signal     : 0
        stackBase  : 0970FC84
        acquiring  : 00000000
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 03365B88
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496713036019
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 03365BA8
          patchArea : 0x0
          interval : 60000 msecs
          lastTime : 1496713036062
          limit    : 4
          count    : 0
        vector     : 0
        prevTime   : 0
        currTime   : 0
        readyTime  : 1496713057133
        currStart  : 1496713165686
        currEnd    : 1496719565686
tests end

    SW900 20-Dec-2020 10:59:06.274 on Reigi {46}
    in ThreadRegistry.GetState
    expl=orphan exited  errval=0x448
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 191[24]
      NodeBase.ThreadRegistry.GetState @ threadregistry.cpp + 299[42]
      NodeBase.Thread.RunningThread @ thread.cpp + 2788[12]
      NodeBase.Thread.Pause @ thread.cpp + 2353[5]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4064[26]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.DeleteLocal completed.
nt>tests begin recover.Ctrl-C
symbols set test.name recover.Ctrl-C
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.18
nt>/ =============== PREPARE TO ENTER CTRL-C, POSSIBLY TWICE ================
nt>/ RECOVER infinite loop
nt>delay 1
nt>symbols assign save.traponrtctimeout traponrtctimeout
nt>cfgparms set traponrtctimeout f
nt>delay 1
nt>recover loop

    SW900 20-Dec-2020 10:59:09.822 on Reigi {47}
    in RecoverCommand.EnsureThread
    expl=recovery thread created  errval=0x0
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 191[24]
      NodeTools.RecoverCommand.EnsureThread @ ntincrement.cpp + 4417[42]
      NodeTools.RecoverCommand.ProcessCommand @ ntincrement.cpp + 4436[9]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 443[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 627[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 291[17]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR903 20-Dec-2020 10:59:10.585 on Reigi {48}
    by NodeBase.InitThread (tid=2, nid=0x000059b0)
    for NodeTools.RecoveryThread (tid=15, nid=0x000039f4)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR903 20-Dec-2020 10:59:10.779 on Reigi {49}
    for NodeTools.RecoveryThread (tid=15, nid=0x000039f4)
    signal=2 (SIGINT: Terminal Interrupt)

    THR902 20-Dec-2020 10:59:10.799 on Reigi {50}
    in NodeTools.RecoveryThread (tid=15, nid=0x000039f4): trap number 21
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1674[31]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3506[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1799[0]
      NodeBase.Debug.ft @ debug.cpp + 74[9]
      NodeTools.RecoveryThread.LoopForever @ ntincrement.cpp + 4083[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4024[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>
    THR905 20-Dec-2020 10:59:10.800 on Reigi {51}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000039f4) overrun=316 msecs
delay 1
nt>cfgparms set traponrtctimeout &save.traponrtctimeout
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.Ctrl-C completed.
nt>tests begin recover.Retrap
symbols set test.name recover.Retrap
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.23
nt>/ RECOVER trap during trap recovery
nt>swflags set &flag.threadretrap on
nt>delay 1
nt>recover badptr

    THR902 20-Dec-2020 10:59:14.611 on Reigi {52}
    in NodeTools.RecoveryThread (tid=15, nid=0x000039f4): trap number 22
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 145[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 4113[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 4015[0]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 20-Dec-2020 10:59:14.614 on Reigi {53}
    in NodeTools.RecoveryThread (tid=15, nid=0x000039f4): trap number 23
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 38[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1877[19]
      NodeBase.SE_Handler @ systhread.win.cpp + 145[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeBase.Thread.TrapHandler @ thread.cpp + 3598[0]
      NodeBase.Thread.Start @ thread.cpp + 3148[46]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>
    THR906 20-Dec-2020 10:59:14.617 on Reigi {54}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000039f4)
    signal=11 (SIGSEGV: Invalid Memory Reference)
delay 1
nt>swflags set &flag.threadretrap off
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.Retrap completed.
nt>tests begin recover.ThreadDtorTrap
symbols set test.name recover.ThreadDtorTrap
  OK.
read test.trap.prolog
nt>send &test.name
  OK.
nt>sched start
nt>start
nt>read trap.27
nt>/ RECOVER recovery thread exits and its destructor traps
nt>recover dtortrap

    SW900 20-Dec-2020 10:59:17.447 on Reigi {55}
    in RecoverCommand.EnsureThread
    expl=recovery thread created  errval=0x0
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 191[24]
      NodeTools.RecoverCommand.EnsureThread @ ntincrement.cpp + 4417[42]
      NodeTools.RecoverCommand.ProcessCommand @ ntincrement.cpp + 4436[9]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 443[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 627[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 291[17]
      NodeBase.Thread.Start @ thread.cpp + 3102[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1571[0]
      register_onexit_function @ <unknown file> (err=487)
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR901 20-Dec-2020 10:59:17.448 on Reigi {56}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000026ec)
    signal=0 (Normal Exit)
nt>delay 1
nt>tests end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &test.name
nt>save funcs &test.name
nt>save trace &test.name
nt>clear buffer
nt>send cout
nt>echo Test &test.name completed.
Test recover.ThreadDtorTrap completed.
nt>