
MODULE INITIALIZATION          msecs      invoked at
pre-Module.Startup               480    18:01:03.602
NodeBase.NbModule...                    18:01:04.082
...initialized                    69
NodeTools.NtModule...                   18:01:04.161
...initialized                    38
CodeTools.CtModule...                   18:01:04.207
...initialized                    21
NetworkBase.NwModule...                 18:01:04.238

    NET500 11-Nov-2019 18:01:04.256 on Reigi {1}
...initialized                   125
SessionBase.SbModule...                 18:01:04.372
...initialized                    97
ControlNode.CnModule...                 18:01:04.478
...initialized                     7
SessionTools.StModule...                18:01:04.495
...initialized                    21
MediaBase.MbModule...                   18:01:04.528
...initialized                    15
CallBase.CbModule...                    18:01:04.554
...initialized                    27
PotsBase.PbModule...                    18:01:04.593
...initialized                    22
OperationsNode.OnModule...              18:01:04.627
...initialized                    12
RoutingNode.RnModule...                 18:01:04.650
...initialized                    11
ServiceNode.SnModule...                 18:01:04.673
...initialized                    44
AccessNode.AnModule...                  18:01:04.729
...initialized                    21
                               -----
total initialization time       1161

    NODE500 11-Nov-2019 18:01:04.775 on Reigi {2}
nb>read test.trap.all
nb>/ MAKE RECOVERY TEST THREAD CRITICAL
nb>read test.trap.setup
nb>quit all
  Nothing to quit.
nb>nt
nt>swflags set &flag.reenterthread on
  OK.
nt>read test.tools.setup
nt>stop
  OK.
nt>clear buffer
  OK.
nt>clear selections
  OK.
nt>clear tools
  OK.
nt>set tools f on
  f: OK.
  OK.
nt>/ set scope counts  / enables full function trace if commented out
nt>include all on
  OK.
nt>read test.trap.tools.setup
nt>exclude faction &faction.audit
  OK.
nt>exclude faction &faction.bkgd
  OK.
nt>exclude faction &faction.oper
  OK.
nt>exclude faction &faction.mtce
  OK.
nt>exclude faction &faction.payload
  OK.
nt>include faction &faction.system
  OK.
nt>testcase prolog test.trap.prolog
  OK.
nt>testcase epilog test.trap.epilog
  OK.
nt>recover create
  OK.
nt>swflags set &flag.disablerootthread on
  OK.
nt>testcase begin recover.Return
symbols set testcase.name recover.Return
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.01
nt>/ RECOVER return
nt>recover return
nt>
    THR901 11-Nov-2019 18:01:10.298 on Reigi {3}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000ca7c)
    signal=0 (Normal Exit)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Return completed.
nt>testcase begin recover.SwErr
symbols set testcase.name recover.SwErr
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.02
nt>/ RECOVER swerr
nt>recover swerr
nt>
    THR902 11-Nov-2019 18:01:12.930 on Reigi {4}
    in NodeTools.RecoveryThread (tid=15, nid=0x000056f0): trap number 1
    type=Software Error
    errstr : 0xe
    offset : 0x1
    Function Traceback:
      NodeBase.Debug.SwLog @ debug.cpp + 207[65]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2369[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SwErr completed.
nt>testcase begin recover.BadPtrExit
symbols set testcase.name recover.BadPtrExit
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.24
nt>/ RECOVER dereference bad pointer and exit thread
nt>swflags set &flag.reenterthread off
nt>delay 1
nt>recover badptr
nt>
    THR902 11-Nov-2019 18:01:15.847 on Reigi {5}
    in NodeTools.RecoveryThread (tid=15, nid=0x000056f0): trap number 2
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1921[16]
      NodeBase.SE_Handler @ systhread.win.cpp + 126[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 3850[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3749[0]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR901 11-Nov-2019 18:01:15.848 on Reigi {6}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x000056f0)
    signal=11 (SIGSEGV: Invalid Memory Reference)
delay 2
nt>swflags set &flag.reenterthread on
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 11-Nov-2019 18:01:19.051 on Reigi {7}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeBase.CliThread (tid=9, nid=0x0000a190)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 11-Nov-2019 18:01:19.074 on Reigi {8}
    thread=NodeBase.CliThread (tid=9, nid=0x0000a190) extra msecs=93
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.BadPtrExit completed.
nt>testcase begin recover.BadPtr
symbols set testcase.name recover.BadPtr
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.03
nt>/ RECOVER dereference bad pointer
nt>recover badptr
nt>
    THR902 11-Nov-2019 18:01:20.330 on Reigi {9}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c5b4): trap number 3
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1921[16]
      NodeBase.SE_Handler @ systhread.win.cpp + 126[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 3850[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3749[0]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.BadPtr completed.
nt>testcase begin recover.DivZero
symbols set testcase.name recover.DivZero
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.04
nt>/ RECOVER divide by zero
nt>recover divide
nt>
    THR902 11-Nov-2019 18:01:22.236 on Reigi {10}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c5b4): trap number 4
    type=Signal
    signal : 8 (SIGFPE: Erroneous Arithmetic Operation)
    errval : 0xc0000094
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1921[16]
      NodeBase.SE_Handler @ systhread.win.cpp + 126[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3752[0]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DivZero completed.
nt>testcase begin recover.SIGINT
symbols set testcase.name recover.SIGINT
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.05
nt>/ RECOVER raise interrupt
nt>recover raise SIGINT
nt>
    THR902 11-Nov-2019 18:01:24.151 on Reigi {11}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c5b4): trap number 5
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x0
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2369[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGINT completed.
nt>testcase begin recover.SIGILL
symbols set testcase.name recover.SIGILL
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.06
nt>/ RECOVER raise illegal instruction
nt>recover raise SIGILL
nt>
    THR902 11-Nov-2019 18:01:26.056 on Reigi {12}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c5b4): trap number 6
    type=Signal
    signal : 4 (SIGILL: Illegal Instruction)
    errval : 0x0
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2369[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 11-Nov-2019 18:01:27.195 on Reigi {13}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeBase.CliThread (tid=9, nid=0x0000a190)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 11-Nov-2019 18:01:27.217 on Reigi {14}
    thread=NodeBase.CliThread (tid=9, nid=0x0000a190) extra msecs=64
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGILL completed.
nt>testcase begin recover.SIGTERM
symbols set testcase.name recover.SIGTERM
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.07
nt>/ RECOVER raise termination from kill
nt>recover raise SIGTERM
nt>
    THR902 11-Nov-2019 18:01:28.000 on Reigi {15}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c5b4): trap number 7
    type=Signal
    signal : 15 (SIGTERM: Termination Request)
    errval : 0x0
    TRAP LIMIT EXCEEDED.
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2369[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR906 11-Nov-2019 18:01:28.001 on Reigi {16}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000c5b4)
    signal=15 (SIGTERM: Termination Request)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGTERM completed.
nt>testcase begin recover.SIGBREAK
symbols set testcase.name recover.SIGBREAK
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.08
nt>/ RECOVER raise ctrl-break
nt>recover raise SIGBREAK
nt>
    THR902 11-Nov-2019 18:01:29.911 on Reigi {17}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c020): trap number 8
    type=Signal
    signal : 21 (SIGBREAK: Ctrl-Break)
    errval : 0x0
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2369[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.SIGBREAK completed.
nt>testcase begin recover.abort
symbols set testcase.name recover.abort
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.09
nt>/ ============== PREPARE TO CLICK RETRY, THEN CONTINUE (F5) ==============
nt>/ RECOVER abort
nt>/ Enable breakpoints because of pop-up dialog.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover abort
nt>
    THR902 11-Nov-2019 18:01:35.116 on Reigi {18}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c020): trap number 9
    type=Signal
    signal : 22 (SIGABRT: Abort Request)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1921[16]
      NodeBase.Thread.SignalHandler @ thread.cpp + 2984[11]
      raise @ <unknown file> (err=487)
      abort @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoAbort @ ntincrement.cpp + 3649[8]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3740[0]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 2
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 11-Nov-2019 18:01:38.361 on Reigi {19}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeBase.CliThread (tid=9, nid=0x0000a190)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 11-Nov-2019 18:01:38.380 on Reigi {20}
    thread=NodeBase.CliThread (tid=9, nid=0x0000a190) extra msecs=134
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.abort completed.
nt>testcase begin recover.terminate
symbols set testcase.name recover.terminate
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.10
nt>/ ============== PREPARE TO CLICK RETRY, THEN CONTINUE (F5) ==============
nt>/ RECOVER terminate
nt>/ Enable breakpoints because of pop-up dialog.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover terminate
nt>
    THR902 11-Nov-2019 18:01:43.484 on Reigi {21}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c020): trap number 10
    type=Signal
    signal : 22 (SIGABRT: Abort Request)
    errval : 0x0
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1921[16]
      NodeBase.Thread.SignalHandler @ thread.cpp + 2984[11]
      raise @ <unknown file> (err=487)
      abort @ <unknown file> (err=487)
      terminate @ <unknown file> (err=487)
      NodeTools.RecoveryThread.DoTerminate @ ntincrement.cpp + 3705[8]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3783[0]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 2
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.terminate completed.
nt>testcase begin recover.KillLocal
symbols set testcase.name recover.KillLocal
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.11
nt>/ RECOVER kill this
nt>recover trap t SIGPURGE
nt>
    THR902 11-Nov-2019 18:01:48.279 on Reigi {22}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c020): trap number 11
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x0
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Thread.Suspend @ thread.cpp + 3311[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2369[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 0344C200
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 034C9488
        NodeBase.SysThread
        this : 034C9488
        patchArea : 0x0
        nthread  : 00000334
        nid      : c020
        status   : 000
        event    : 00000330
        guard    : 0000034C
        priority : 1
        signal   : 0
      daemon  : 030AA040 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 034CCD90
        patchArea : 0x0
        stackBase  : 067AFA7C
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 034CCDA8
          patchArea : 0x0
          interval : 600000000
          lastTime : 7031913173082
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 034CCDC8
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032082277506
          limit    : 4
          count    : 3
        status     : unspecified
        blocked    : ready
        entered    : true
        waiting    : false
        locked     : true
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevUsecs  : 2340828
        currUsecs  : 0
        readyTime  : 7032115921215
        currStart  : 7032115924242
        currEnd    : 7032130724242
      test   : 0
      signal : 126
testcase end

    THR901 11-Nov-2019 18:01:48.279 on Reigi {23}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000c020)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.KillLocal completed.
nt>testcase begin recover.KillRemote
symbols set testcase.name recover.KillRemote
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.12
nt>/ RECOVER kill remotely
nt>recover trap f SIGPURGE
nt>
    THR903 11-Nov-2019 18:01:50.395 on Reigi {24}
    by NodeBase.CliThread (tid=9, nid=0x0000a190)
    for NodeTools.RecoveryThread (tid=15, nid=0x0000840c)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

    THR902 11-Nov-2019 18:01:50.399 on Reigi {25}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000840c): trap number 12
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1769[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3505[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1868[0]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Thread.SetTrap @ thread.cpp + 2917[11]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1769[0]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1739[0]
      NodeBase.Thread.Pause @ thread.cpp + 2370[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3795[10]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 0344C32C
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 034CA528
        NodeBase.SysThread
        this : 034CA528
        patchArea : 0x0
        nthread  : 00000490
        nid      : 840c
        status   : 000
        event    : 0000049C
        guard    : 000004A0
        priority : 1
        signal   : 0
      daemon  : 030AA040 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 034CC8F8
        patchArea : 0x0
        stackBase  : 08F8FD18
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 034CC910
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032115959802
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 034CC930
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032137155762
          limit    : 4
          count    : 1
        status     : unspecified
        blocked    : ready
        entered    : true
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevUsecs  : 14
        currUsecs  : 0
        readyTime  : 7032115989215
        currStart  : 7032137109603
        currEnd    : 2000000
      test   : 0
      signal : 0
testcase end

    THR901 11-Nov-2019 18:01:50.400 on Reigi {26}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000840c)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 11-Nov-2019 18:01:51.506 on Reigi {27}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeBase.CliThread (tid=9, nid=0x0000a190)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 11-Nov-2019 18:01:51.537 on Reigi {28}
    thread=NodeBase.CliThread (tid=9, nid=0x0000a190) extra msecs=41
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.KillRemote completed.
nt>testcase begin recover.InfiniteLoop
symbols set testcase.name recover.InfiniteLoop
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.13
nt>/ RECOVER infinite loop
nt>/ Enable use of SIGYIELD to kill thread that runs too long.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled f
nt>symbols assign save.traponrtctimeout traponrtctimeout
nt>cfgparms set traponrtctimeout t
nt>delay 1
nt>recover loop
nt>
    THR903 11-Nov-2019 18:01:54.992 on Reigi {29}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeTools.RecoveryThread (tid=15, nid=0x0000c79c)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR902 11-Nov-2019 18:01:55.003 on Reigi {30}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c79c): trap number 13
    type=Signal
    signal : 123 (SIGYIELD: Running Unpreemptably Too Long)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1769[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3505[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1868[0]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeTools.RecoveryThread.LoopForever @ ntincrement.cpp + 3814[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3755[0]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 2
nt>cfgparms set traponrtctimeout &save.traponrtctimeout
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.InfiniteLoop completed.
nt>testcase begin recover.StackOverflow
symbols set testcase.name recover.StackOverflow
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.14
nt>/ ============== THE STACK OVERFLOW MAY TAKE TIME TO OCCUR ===============
nt>/ RECOVER stack overflow
nt>/ Enable breakpoints to provide time for overflow.
nt>symbols assign save.breakenabled breakenabled
nt>cfgparms set breakenabled t
nt>delay 1
nt>recover stack
nt>
    THR902 11-Nov-2019 18:02:01.054 on Reigi {31}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c79c): trap number 14
    type=Signal
    signal : 124 (SIGSTACK1: Stack Overflow: Attempt Recovery)
    errval : 0x1f42
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.StackCheck @ thread.cpp + 3022[14]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1876[0]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3836[11]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      ...1997 functions omitted.
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
      NodeTools.RecoveryThread.RecurseForever @ ntincrement.cpp + 3838[12]
delay 2
nt>cfgparms set breakenabled &save.breakenabled
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 11-Nov-2019 18:02:04.251 on Reigi {32}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeBase.CliThread (tid=9, nid=0x0000a190)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 11-Nov-2019 18:02:04.326 on Reigi {33}
    thread=NodeBase.CliThread (tid=9, nid=0x0000a190) extra msecs=131
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.StackOverflow completed.
nt>testcase begin recover.MutexBlock
symbols set testcase.name recover.MutexBlock
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.19
nt>/ RECOVER block while holding mutex
nt>recover mutexblock
nt>
    SW900 11-Nov-2019 18:02:06.442 on Reigi {34}
    in Thread.EnterBlockingOperation
    errval=mutex holder  offset=0x1
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 99[22]
      NodeBase.Debug.SwLog @ debug.cpp + 219[25]
      NodeBase.Thread.EnterBlockingOperation @ thread.cpp + 1607[55]
      NodeBase.Thread.Pause @ thread.cpp + 2367[14]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3758[7]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexBlock completed.
nt>testcase begin recover.MutexExit
symbols set testcase.name recover.MutexExit
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.21
nt>/ RECOVER exit while holding mutex
nt>recover mutexexit
nt>
    THR907 11-Nov-2019 18:02:08.268 on Reigi {35}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000c79c)
    mutexes=1

    THR901 11-Nov-2019 18:02:08.268 on Reigi {36}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000c79c)
    signal=0 (Normal Exit)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexExit completed.
nt>testcase begin recover.MutexTrap
symbols set testcase.name recover.MutexTrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.22
nt>/ RECOVER trap while holding mutex
nt>recover mutextrap
nt>
    THR907 11-Nov-2019 18:02:10.187 on Reigi {37}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000c23c)
    mutexes=1

    THR902 11-Nov-2019 18:02:10.188 on Reigi {38}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c23c): trap number 15
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThread.Suspend @ systhread.win.cpp + 316[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2369[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.MutexTrap completed.
nt>testcase begin recover.TrapInRecover
symbols set testcase.name recover.TrapInRecover
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.15
nt>/ RECOVER trap during recovery
nt>swflags set &flag.recovertrap on
nt>delay 1
nt>recover swerr
nt>
    THR902 11-Nov-2019 18:02:13.178 on Reigi {39}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c23c): trap number 16
    type=Software Error
    errstr : 0xe
    offset : 0x1
    Function Traceback:
      NodeBase.ThreadRegistry.FindThread @ threadregistry.cpp + 197[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2369[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR902 11-Nov-2019 18:02:13.182 on Reigi {40}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000c23c): trap number 17
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    TRAP DURING RECOVERY.
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1921[16]
      NodeBase.SE_Handler @ systhread.win.cpp + 126[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeTools.RecoveryThread.UseBadPointer @ ntincrement.cpp + 3850[0]
      NodeTools.RecoveryThread.Recover @ ntincrement.cpp + 3827[0]
      NodeBase.Thread.Start @ thread.cpp + 3079[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 2
nt>swflags set &flag.recovertrap off
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 11-Nov-2019 18:02:16.386 on Reigi {41}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeBase.CliThread (tid=9, nid=0x0000a190)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 11-Nov-2019 18:02:16.386 on Reigi {42}
    thread=NodeBase.CliThread (tid=9, nid=0x0000a190) extra msecs=72
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.TrapInRecover completed.
nt>testcase begin recover.ThreadCtorTrap
symbols set testcase.name recover.ThreadCtorTrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.20
nt>/ RECOVER thread constructor trap
nt>/ InitThread will trap when it invokes RecoveryDaemon.CreateThread
nt>/ to recreate the recovery thread.
nt>recover ctortrap
nt>
    THR901 11-Nov-2019 18:02:17.578 on Reigi {43}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000c23c)
    signal=0 (Normal Exit)

    THR900 11-Nov-2019 18:02:17.586 on Reigi {44}
    thread=NodeBase.Thread (tid=15, nid=0x0000b2c0)
    Function Traceback:
      NodeBase.SysThreadStack.FuncDepth @ systhreadstack.win.cpp + 271[5]
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Debug.noop @ debug.cpp + 124[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1652[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
    Thread Data:
      NodeBase.Thread
      this : 0344C6B0
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 034DCBF0
        NodeBase.SysThread
        this : 034DCBF0
        patchArea : 0x0
        nthread  : 00000324
        nid      : b2c0
        status   : 000
        event    : 000004AC
        guard    : 000004B0
        priority : 1
        signal   : 0
      daemon  : 030AA040 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 034CCE38
        patchArea : 0x0
        stackBase  : 00000000
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 034CCE50
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032408947719
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 034CCE70
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032408947721
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 0
        currUsecs  : 0
        readyTime  : 18446744073709551615
        currStart  : 0
        currEnd    : 0
testcase end

    THR902 11-Nov-2019 18:02:17.595 on Reigi {45}
    in NodeBase.InitThread (tid=2, nid=0x0000cbd4): trap number 18
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Debug.noop @ debug.cpp + 124[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1652[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

    SW900 11-Nov-2019 18:02:17.595 on Reigi {46}
    in Orphans.ExitNow
    errval=orphan exited  offset=0xb2c0
    Function Traceback:
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Thread.EnterBlockingOperation @ thread.cpp + 1588[11]
      NodeBase.SysMutex.Acquire @ sysmutex.win.cpp + 91[0]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Pause @ thread.cpp + 2370[12]
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.ThreadCtorTrap completed.
nt>testcase begin recover.DaemonReenable
symbols set testcase.name recover.DaemonReenable
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.25
nt>/ RECOVER disable daemon; kill thread; enable daemon; thread recreated
nt>daemons set 9 off
nt>delay 1
nt>sched kill 15
nt>
    THR903 11-Nov-2019 18:02:20.951 on Reigi {47}
    by NodeBase.CliThread (tid=9, nid=0x0000a190)
    for NodeTools.RecoveryThread (tid=15, nid=0x0000a708)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

    THR902 11-Nov-2019 18:02:20.955 on Reigi {48}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000a708): trap number 19
    type=Signal
    signal : 126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1769[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3505[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1868[0]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.SysThreadStack.TrapIsOk @ systhreadstack.win.cpp + 317[11]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1766[24]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1739[0]
      NodeBase.Thread.Pause @ thread.cpp + 2370[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3795[10]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeTools.RecoveryThread
      this : 0344C7DC
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 034DD130
        NodeBase.SysThread
        this : 034DD130
        patchArea : 0x0
        nthread  : 000004B4
        nid      : a708
        status   : 000
        event    : 00000450
        guard    : 00000474
        priority : 1
        signal   : 0
      daemon  : 030AA040 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 034CC8F8
        patchArea : 0x0
        stackBase  : 0929FE94
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 034CC910
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032409127693
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 034CC930
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032442711179
          limit    : 4
          count    : 1
        status     : unspecified
        blocked    : ready
        entered    : true
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 1
        recovering : false
        logged     : true
        exiting    : false
        action     : 0
        signal     : 126
        vector     : 0
        prevUsecs  : 49
        currUsecs  : 0
        readyTime  : 7032409186913
        currStart  : 7032442678094
        currEnd    : 2000000
      test   : 0
      signal : 0
delay 2

    THR901 11-Nov-2019 18:02:20.956 on Reigi {49}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000a708)
    signal=126 (SIGPURGE: Suicided [errval = 0] or Killed [errval > 0])

  * THR300 11-Nov-2019 18:02:20.956 on Reigi {50}
    Alarm ON: DAEMON9 (Thread(s) unavailable: recover)
    daemon=recover target=1 actual=0
nt>daemons set 9 on
nt>
    THR300 11-Nov-2019 18:02:22.979 on Reigi {51}
    Alarm OFF: DAEMON9 (Thread(s) unavailable: recover)
    daemon=recover target=1 actual=1
delay 1
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 11-Nov-2019 18:02:25.211 on Reigi {52}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeBase.CliThread (tid=9, nid=0x0000a190)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 11-Nov-2019 18:02:25.231 on Reigi {53}
    thread=NodeBase.CliThread (tid=9, nid=0x0000a190) extra msecs=123
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DaemonReenable completed.
nt>testcase begin recover.DaemonRetrap
symbols set testcase.name recover.DaemonRetrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.26
nt>/ RECOVER daemon retraps trying to recreate thread; reenable to create thread
nt>swflags set &flag.threadctorretrap on
nt>delay 1
nt>recover ctortrap
nt>
    THR901 11-Nov-2019 18:02:27.714 on Reigi {54}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000c364)
    signal=0 (Normal Exit)

    THR900 11-Nov-2019 18:02:27.719 on Reigi {55}
    thread=NodeBase.Thread (tid=15, nid=0x00009084)
    Function Traceback:
      NodeBase.SysThreadStack.FuncDepth @ systhreadstack.win.cpp + 271[5]
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Debug.noop @ debug.cpp + 124[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1652[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
    Thread Data:
      NodeBase.Thread
      this : 0344CA34
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 034C8D88
        NodeBase.SysThread
        this : 034C8D88
        patchArea : 0x0
        nthread  : 0000048C
        nid      : 9084
        status   : 000
        event    : 00000444
        guard    : 000004BC
        priority : 1
        signal   : 0
      daemon  : 030AA040 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 034CC118
        patchArea : 0x0
        stackBase  : 00000000
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 034CC130
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032510308804
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 034CC150
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032510308807
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 0
        currUsecs  : 0
        readyTime  : 18446744073709551615
        currStart  : 0
        currEnd    : 0
delay 2

    THR902 11-Nov-2019 18:02:27.721 on Reigi {56}
    in NodeBase.InitThread (tid=2, nid=0x0000cbd4): trap number 20
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Debug.noop @ debug.cpp + 124[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1652[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

    SW900 11-Nov-2019 18:02:27.721 on Reigi {57}
    in Orphans.ExitNow
    errval=orphan exited  offset=0x9084
    Function Traceback:
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Thread.InitialMsecs @ thread.cpp + 1959[11]
      NodeBase.Thread.Suspend @ thread.cpp + 3332[0]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1741[0]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]

    THR900 11-Nov-2019 18:02:27.727 on Reigi {58}
    thread=NodeBase.Thread (tid=15, nid=0x0000c748)
    Function Traceback:
      NodeBase.SysThreadStack.FuncDepth @ systhreadstack.win.cpp + 271[5]
      NodeBase.FunctionTrace.Capture @ functiontrace.cpp + 161[5]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Debug.noop @ debug.cpp + 124[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1652[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
    Thread Data:
      NodeBase.Thread
      this : 0344CB60
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 034C8F80
        NodeBase.SysThread
        this : 034C8F80
        patchArea : 0x0
        nthread  : 000004A0
        nid      : c748
        status   : 000
        event    : 000004C0
        guard    : 000004C4
        priority : 1
        signal   : 0
      daemon  : 030AA040 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 034CC8F8
        patchArea : 0x0
        stackBase  : 00000000
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 034CC910
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032510377201
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 034CC930
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032510377203
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : false
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 0
        currUsecs  : 0
        readyTime  : 18446744073709551615
        currStart  : 0
        currEnd    : 0

    THR902 11-Nov-2019 18:02:27.729 on Reigi {59}
    in NodeBase.InitThread (tid=2, nid=0x0000cbd4): trap number 21
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Debug.noop @ debug.cpp + 124[11]
      NodeBase.Thread.EnterThread @ thread.cpp + 1652[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

    SW900 11-Nov-2019 18:02:27.729 on Reigi {60}
    in Orphans.ExitNow
    errval=orphan exited  offset=0xc748
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 99[22]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Thread.MakeUnpreemptable @ thread.cpp + 2254[48]
      NodeBase.ContextSwitches.AddSwitch @ thread.cpp + 390[0]
      NodeBase.ContextSwitches.AddSwitch @ thread.cpp + 379[12]
      NodeBase.Thread.Pause @ thread.cpp + 2370[12]

  * THR300 11-Nov-2019 18:02:27.730 on Reigi {61}
    Alarm ON: DAEMON9 (Thread(s) unavailable: recover)
    daemon=recover target=1 actual=0
nt>daemons set 9 on
nt>
    THR300 11-Nov-2019 18:02:29.761 on Reigi {62}
    Alarm OFF: DAEMON9 (Thread(s) unavailable: recover)
    daemon=recover target=1 actual=1
delay 1
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DaemonRetrap completed.
nt>testcase begin recover.DeleteRemote
symbols set testcase.name recover.DeleteRemote
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.16
nt>/ RECOVER destroy remotely
nt>/ After deleting the thread, give it time to wake up and exit.
nt>recover delete f
nt>
    THR900 11-Nov-2019 18:02:33.553 on Reigi {63}
    thread=NodeBase.Thread (tid=15, nid=0x000030b0)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 196[5]
      NodeBase.Thread.~Thread @ thread.cpp + 1181[16]
      NodeTools.RecoveryThread.~RecoveryThread @ ntincrement.cpp + 3596[15]
      NodeTools.RecoveryThread.`scalar deleting destructor' @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Destroy @ singleton.h + 104[34]
      NodeTools.RecoverCommand.ProcessCommand @ ntincrement.cpp + 4197[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.ReadCommand.ProcessCommand @ nbincrement.cpp + 2193[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.ReadCommand.ProcessCommand @ nbincrement.cpp + 2193[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 345[17]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 0344CC8C
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 06C3E040
        NodeBase.SysThread
        this : 06C3E040
        patchArea : 0x0
        nthread  : 00000448
        nid      : 30b0
        status   : 000
        event    : 000004A0
        guard    : 000004C4
        priority : 1
        signal   : 0
      daemon  : 030AA040 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 034CC8F8
        patchArea : 0x0
        stackBase  : 08F8FF44
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 034CC910
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032530748451
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 034CC930
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032530748453
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : sleeping
        entered    : true
        waiting    : false
        locked     : false
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 51
        currUsecs  : 0
        readyTime  : 7032530768845
        currStart  : 7032530774457
        currEnd    : 0
delay 8

    SW900 11-Nov-2019 18:02:34.766 on Reigi {64}
    in Orphans.ExitNow
    errval=orphan exited  offset=0x30b0
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 99[22]
      NodeBase.Debug.SwLog @ debug.cpp + 219[25]
      NodeBase.Orphans.ExitNow @ thread.cpp + 731[42]
      NodeBase.Thread.RunningThread @ thread.cpp + 2796[12]
      NodeBase.Thread.ExitBlockingOperation @ thread.cpp + 1720[7]
      NodeBase.Thread.Pause @ thread.cpp + 2370[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3795[10]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DeleteRemote completed.
nt>testcase begin recover.DeleteLocal
symbols set testcase.name recover.DeleteLocal
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.17
nt>/ RECOVER destroy this
nt>recover delete t
nt>
    THR900 11-Nov-2019 18:02:44.469 on Reigi {65}
    thread=NodeBase.Thread (tid=15, nid=0x0000a4c8)
    Function Traceback:
      NodeBase.SysThreadStack.Display @ systhreadstack.win.cpp + 196[5]
      NodeBase.Thread.~Thread @ thread.cpp + 1181[16]
      NodeTools.RecoveryThread.~RecoveryThread @ ntincrement.cpp + 3596[15]
      NodeTools.RecoveryThread.`scalar deleting destructor' @ <unknown file> (err=487)
      NodeBase.Singleton<NodeTools.RecoveryThread>.Destroy @ singleton.h + 104[34]
      NodeTools.RecoveryThread.DoDelete @ ntincrement.cpp + 3661[0]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3746[0]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
    Thread Data:
      NodeBase.Thread
      this : 0344CDB8
      patchArea : 0x0
      pid      : 1
      seq      : 1
      link     : 00000000
      assigned : true
      orphaned : 0
      corrupt  : false
      logged   : false
      systhrd : 034D5078
        NodeBase.SysThread
        this : 034D5078
        patchArea : 0x0
        nthread  : 00000474
        nid      : a4c8
        status   : 000
        event    : 000004C8
        guard    : 000004CC
        priority : 1
        signal   : 0
      daemon  : 030AA040 NodeTools.RecoveryDaemon
      tid     : 15
      faction : 6
      deleted : false
      msgq    : 
        tail : 00000000
        diff : 8
      priv    : 
        NodeBase.ThreadPriv
        this : 034CC8F8
        patchArea : 0x0
        stackBase  : 0AA7F8B8
        unpreempts : 1
        unprotects : 0
        mutexes    : 0
        acquiring  : 00000000
        swlogs     : 0
        rtcLbc     : 
          NodeBase.LeakyBucketCounter
          this : 034CC910
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032568849912
          limit    : 6
          count    : 0
        trapLbc    : 
          NodeBase.LeakyBucketCounter
          this : 034CC930
          patchArea : 0x0
          interval : 600000000
          lastTime : 7032568849914
          limit    : 4
          count    : 0
        status     : unspecified
        blocked    : ready
        entered    : true
        waiting    : false
        locked     : true
        traceMsg   : false
        tracing    : false
        autostop   : false
        warned     : false
        trap       : false
        traps      : 0
        recovering : false
        logged     : false
        exiting    : false
        action     : 0
        signal     : 0
        vector     : 0
        prevUsecs  : 9
        currUsecs  : 21
        readyTime  : 7032677846268
        currStart  : 7032677850648
        currEnd    : 7032690650648
testcase end

    SW900 11-Nov-2019 18:02:44.471 on Reigi {66}
    in Orphans.ExitNow
    errval=orphan exited  offset=0xa4c8
    Function Traceback:
      NodeBase.Debug.GenerateSwLog @ debug.cpp + 99[22]
      NodeBase.Debug.SwLog @ debug.cpp + 219[25]
      NodeBase.Orphans.ExitNow @ thread.cpp + 731[42]
      NodeBase.Singletons.BindInstance @ singletons.cpp + 77[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2369[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 11-Nov-2019 18:02:45.606 on Reigi {67}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeBase.CliThread (tid=9, nid=0x0000a190)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 11-Nov-2019 18:02:45.640 on Reigi {68}
    thread=NodeBase.CliThread (tid=9, nid=0x0000a190) extra msecs=36
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.DeleteLocal completed.
nt>testcase begin recover.Ctrl-C
symbols set testcase.name recover.Ctrl-C
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.18
nt>/ =============== PREPARE TO ENTER CTRL-C, POSSIBLY TWICE ================
nt>/ RECOVER infinite loop
nt>delay 1
nt>symbols assign save.traponrtctimeout traponrtctimeout
nt>cfgparms set traponrtctimeout f
nt>delay 1
nt>recover loop
nt>
    THR903 11-Nov-2019 18:02:49.605 on Reigi {69}
    for NodeBase.CliThread (tid=9, nid=0x0000a190)
    signal=2 (SIGINT: Terminal Interrupt)

    THR903 11-Nov-2019 18:02:49.866 on Reigi {70}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeTools.RecoveryThread (tid=15, nid=0x0000ba28)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR903 11-Nov-2019 18:02:51.251 on Reigi {71}
    for NodeTools.RecoveryThread (tid=15, nid=0x0000ba28)
    signal=2 (SIGINT: Terminal Interrupt)

    THR902 11-Nov-2019 18:02:51.272 on Reigi {72}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000ba28): trap number 22
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1769[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3505[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1868[0]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeTools.RecoveryThread.LoopForever @ ntincrement.cpp + 3814[12]
      NodeTools.RecoveryThread.Enter @ ntincrement.cpp + 3755[0]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)

    THR905 11-Nov-2019 18:02:51.272 on Reigi {73}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000ba28) extra msecs=1381

    THR902 11-Nov-2019 18:02:51.286 on Reigi {74}
    in NodeBase.CliThread (tid=9, nid=0x0000a190): trap number 23
    type=Signal
    signal : 2 (SIGINT: Terminal Interrupt)
    errval : 0x3
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.ExitIfSafe @ thread.cpp + 1769[27]
      NodeBase.Thread.TrapCheck @ thread.cpp + 3505[0]
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1868[0]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.CoutThread.Spool @ coutthread.cpp + 122[11]
      NodeBase.CliBuffer.GetLine @ clibuffer.cpp + 364[9]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 670[22]
      NodeBase.ReadCommand.ProcessCommand @ nbincrement.cpp + 2193[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.ReadCommand.ProcessCommand @ nbincrement.cpp + 2193[0]
      NodeBase.CliThread.InvokeCommand @ clithread.cpp + 464[19]
      NodeBase.CliThread.ReadCommands @ clithread.cpp + 676[0]
      NodeBase.CliThread.Enter @ clithread.cpp + 345[17]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
nt>cfgparms set traponrtctimeout &save.traponrtctimeout
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Ctrl-C completed.
nt>testcase begin recover.Retrap
symbols set testcase.name recover.Retrap
  OK.
read test.trap.prolog
nt>send &testcase.name
  OK.
nt>sched start
nt>start
nt>read trap.23
nt>/ RECOVER trap during trap recovery
nt>swflags set &flag.threadretrap on
nt>delay 1
nt>recover badptr
nt>
    THR902 11-Nov-2019 18:02:55.143 on Reigi {75}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000ba28): trap number 24
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.Thread.FunctionInvoked @ thread.cpp + 1857[9]
      NodeBase.Debug.ft @ debug.cpp + 65[9]
      NodeBase.Thread.UpdateMutexCount @ thread.cpp + 3683[11]
      NodeBase.SysThread.Delay @ systhread.cpp + 107[0]
      NodeBase.Thread.Pause @ thread.cpp + 2369[28]
      NodeBase.InitThread.Enter @ initthread.cpp + 230[9]
      NodeBase.Thread.Start @ thread.cpp + 3117[15]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)
      <unknown function> (err=126)

    THR902 11-Nov-2019 18:02:55.148 on Reigi {76}
    in NodeTools.RecoveryThread (tid=15, nid=0x0000ba28): trap number 25
    type=Signal
    signal : 11 (SIGSEGV: Invalid Memory Reference)
    errval : 0xc0000005
    Function Traceback:
      NodeBase.SignalException.SignalException @ signalexception.cpp + 40[12]
      NodeBase.Thread.HandleSignal @ thread.cpp + 1921[16]
      NodeBase.SE_Handler @ systhread.win.cpp + 126[13]
      _unDNameEx @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      is_exception_typeof @ <unknown file> (err=487)
      _CxxFrameHandler3 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      RtlInterlockedCompareExchange64 @ <unknown file> (err=487)
      KiUserExceptionDispatcher @ <unknown file> (err=487)
      NodeBase.Thread.TrapHandler @ thread.cpp + 3575[0]
      NodeBase.Thread.Start @ thread.cpp + 3164[46]
      NodeBase.Thread.EnterThread @ thread.cpp + 1672[0]
      BaseThreadInitThunk @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
      RtlGetAppContainerNamedObjectPath @ <unknown file> (err=487)
delay 2

    THR906 11-Nov-2019 18:02:55.152 on Reigi {77}
    thread=NodeTools.RecoveryThread (tid=15, nid=0x0000ba28)
    signal=11 (SIGSEGV: Invalid Memory Reference)
nt>swflags set &flag.threadretrap off
nt>testcase end
read test.trap.epilog
nt>delay 1
nt>stop
nt>sched stop
nt>sched show &testcase.name
nt>
    THR903 11-Nov-2019 18:02:58.306 on Reigi {78}
    by NodeBase.InitThread (tid=2, nid=0x0000cbd4)
    for NodeBase.CliThread (tid=9, nid=0x0000a190)
    signal=123 (SIGYIELD: Running Unpreemptably Too Long)

    THR905 11-Nov-2019 18:02:58.339 on Reigi {79}
    thread=NodeBase.CliThread (tid=9, nid=0x0000a190) extra msecs=81
save funcs &testcase.name
nt>save trace &testcase.name
nt>clear buffer
nt>send cout
nt>print Testcase &testcase.name completed.
Testcase recover.Retrap completed.
nt>